# Generated by Django 4.2.7 on 2023-12-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeecafes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.TextField(default='username', max_length=10),
            preserve_default=False,
        ),
    ]
