# Generated by Django 4.2.7 on 2024-01-03 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffeecafes', '0004_remove_review_image_reviewimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeecafe',
            name='image',
        ),
        migrations.CreateModel(
            name='CoffeeCafeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeecafes.coffeecafe')),
            ],
        ),
    ]
