# Generated by Django 4.2.7 on 2024-02-27 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coffeecafes', '0005_remove_coffeecafe_image_coffeecafeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeecafe',
            name='note',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coffeecafe',
            name='parking',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coffeecafe',
            name='toilet',
            field=models.FloatField(default=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coffeecafe',
            name='wifi',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='user_review',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
