# Generated by Django 4.2.7 on 2024-02-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeecafes', '0008_remove_review_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeecafe',
            name='note',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='coffeecafe',
            name='parking',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='coffeecafe',
            name='toilet',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='coffeecafe',
            name='wifi',
            field=models.FloatField(default=1),
        ),
    ]
