# Generated by Django 4.2.7 on 2024-02-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeecafes', '0009_alter_coffeecafe_note_alter_coffeecafe_parking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='username',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
