# Generated by Django 4.2.7 on 2024-02-27 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeecafes', '0010_review_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='username',
            new_name='name',
        ),
    ]
