# Generated by Django 4.2.7 on 2024-02-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeecafes', '0011_rename_username_review_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeecafe',
            name='coffee',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='coffeecafe',
            name='plug',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='coffeecafe',
            name='seat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='coffeecafe',
            name='vibe',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='coffeecafe',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='coffeecafe',
            name='lng',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='coffeecafe',
            name='toilet',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='coffeecafe',
            name='wifi',
            field=models.FloatField(default=0),
        ),
    ]
