# Generated by Django 3.2.13 on 2023-10-25 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeCafe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('total_score', models.FloatField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=500)),
                ('date', models.DateField()),
                ('score', models.FloatField()),
                ('type', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeecafes.coffeecafe')),
            ],
        ),
    ]
